---
title: "Introduction to R and analytic Programming"
date: "2024-12-23 (Last update: `r Sys.Date()`)"
author: "Yuchen Li & Thomas O'Neil"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: 
link-citations: yes
github-repo: DrThomasOneil/analysis-user-group
---

```html
<head>
  <script>
    // Set the valid password
    const validPassword = "pw"; 
  
    document.addEventListener("DOMContentLoaded", () => {
      document.body.style.display = "none"; 
  
      function validatePassword() {
        let authenticated = false;
  
        while (!authenticated) {
          const password = prompt("Enter password:");
  
          if (password === validPassword) {
            document.body.style.display = "block"; 
            authenticated = true; // Exit the loop
          } else {
            alert("Incorrect password. Please try again.");
          }
        }
      }
  
      // Call the password validation function
      validatePassword();
    });
  </script>
  
  <script src="../adit/quotes.js"></script>
  <script>
    const noteSymbol = "&#9834;";
    function showRandomQuote() {
      const randomIndex = Math.floor(Math.random() * quotes.length);
      const quoteObj = quotes[randomIndex];
      const quoteElement = document.getElementById("quote-box");
  
      const formattedQuote = `
        ${noteSymbol} ${quoteObj.quote} ${noteSymbol}<br>
        <em>${quoteObj.song}</em><br>
        <strong>${quoteObj.artist}</strong>
      `;
  
      quoteElement.innerHTML = formattedQuote;
    }
  
    document.addEventListener("DOMContentLoaded", showRandomQuote);
  </script>
</head>
``` 

# Welcome!
 
This is the sub-repository containing the tutorials and workshop notes for the introduction to R and analytic programming. 

[Get started →](https://drthomasoneil.github.io/analysis-user-group/r-tutorial/_book/introduction.html)


```{r include=F}
# <div class="hint-info">
# <strong>Info:</strong> This is to accentuate important points.  
# </div>
# 
# <div class="hint-success">
# <strong>Success:</strong> This is good for showing positive actions or achievements.  
# </div>  
# 
# <div class="hint-warning">
# <strong>Warning:</strong> This is important information or non-critical warnings.  
# </div>
# 
# <div class="hint-danger">
# <strong>Danger:</strong> This highlights destructive actions or critical information.
# </div>
```
 
```{r}
getwd()
```
 
```{r, eval=FALSE, include=F, message=F}
bookdown::render_book() 
```

```{r, echo=F, eval=FALSE, include=F}
servr::daemon_stop(3)
bookdown::serve_book() 
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
 
<e>
