---
title: ""
output:
  workflowr::wflow_html:
    toc: no
---

## **Flow Cytometry Analysis**: Leveraging Software and R for Deeper Insights

This DRSN series explores how both traditional software and R-based approaches can complement each other in flow cytometry analysis. Whether you rely on software, are curious about coding, or want to integrate both approaches, this series will help you expand your analysis toolkit.

<wimr>  

#### **Tuesday 15th April** (WIMR Seminar Room & Zoom)

##### [Seminar (11am)](https://drthomasoneil.github.io/Digital-Research-Skills-Network/202504_Seminar.html)

We’ll first compare the strengths of GUI-based tools like FlowJo with the flexibility of coding.    
**Speakers**: Suat Dervish, Nicole Fewings    
(lunch from 12pm)

##### [In-focus Workshop (1 – 3pm)](https://drthomasoneil.github.io/Digital-Research-Skills-Network/202504_InFocus.html)

We’ll hold a discussion on key analytic considerations and available R packages. 

**Speakers**: Givanna Putri, Felix Marsh-Wakefield, Elijah Willie

#### **Monday 28th April** (WIMR Seminar Room & Zoom)

##### [Programming workshop (1 – 3pm)](https://drthomasoneil.github.io/Digital-Research-Skills-Network/202504_Workshop.html)

The final hands-on session will introduce participants to performing flow cytometry analysis in R, providing a practical workflow for data visualization, summarization, and reproducibility. 

**Demonstrators**: Thomas O’Neil

<wimr>

## Sign up for these events:    


<iframe width="900px" height="900px" src="https://forms.office.com/r/FKdfCd1iW1?embed=true" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>
