---
title: ""
output:
  workflowr::wflow_html:
    toc: no
---
<div style = "text-align: center">

#### **Wednesday 13th August** (WIMR C2.31)

##### **Coding Club (1pm - 3pm)**
Bring your codes data, and questions. Enjoy the time and space for networking, collaboration, helping each other, or focusing on coding/analysis/statistics.

<span style="display:inline-block; width:80%;"><hr></span>

#### **Wednesday 20th August** (WIMR Seminar Room & Zoom)

##### **Bring your own data! (12pm - 2pm)**

Join **Thomas O'Neil** for a short tutorial on how to find, download and get started processing publicly available transcriptomics data.

If you have a dataset or paper you've been looking at, bring it along and we can help you download and process for immediate results!


<span style="display:inline-block; width:80%;"><hr></span>

#### **Wednesday 27th August** (CASB - C24-10.05.5307 1 - 2pm)

##### **Data Insight Forum (1pm - 3pm)**
Connect directly as a community of analysts, present your work and get feedback from others. The general structure will be round-table updates and 5-minute presentations on real-world data analysis questions.

<br>
