---
output:
  workflowr::wflow_html:
    toc: no
---

## When to Stick with Software and When to Code for Flow Cytometry Analysis
 
<div style="text-align: center">

<read-time><span style="color:black;"><font size="3">**Tuesday 15th April, 11 am**</font></span></read-time>

<read-time><span style="color:black;"><font size="3">WIMR Seminar Room</font></span></read-time>

<read-time>[Zoom Link]()</read-time>

<span style="color:#dd571c;"><font size="3">**Lunch Provided**</font></span>

</div>

</wimr>

<span style="color:black;">Flow cytometry analysis is often performed using intuitive, UI-based software like FlowJo, but as datasets grow in complexity, programming tools like R offer powerful alternatives. This seminar will contrast standard software workflows with programming-based approaches, highlighting where GUI-based tools excel and where scripting can unlock deeper insights. We’ll explore the strengths and limitations of both, covering practical examples, key decision points, and a case study where coding provided the flexibility needed to push analysis beyond software constraints.

**Speakers**:

- Suat Dervish    
- Nicole Fewings    
<br>

